### ISSUE TITLE
Sonarcloud bug

### ISSUE THREAD

**Issue by Sasikumar77** [fssa-batch3/sec_c_sec_c_sasikumar.saminathan__corejava_project_2#1]
### ConnectionUtil snippet
             try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			try(Connection con = DriverManager.getConnection(url, userName, passWord)){
			logger.info("connection successful");
			return con;
			}

		} catch (Exception e) {
			throw new ClassNotFoundException("Unable to connect to the database");
		}

I'm facing an issue in sonarcloud there is a bug for this snippet **Use try-with-resources or close this "Connection" in a "finally" clause.** but if i am use try-with-resources or using finally to close this connection
`Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.`
it's throwing this error while i am running my DAO testcases.
Could you please provide some guidance to resolve this issue?

**Comment by msbAtGit** [comment]
This is acceptable.

**Comment by cyber-sparky** [comment]
```
public class ConnectionUtil {
	private ConnectionUtil() {
//	private constructor
	}

	/**
	 * Get a connection to the database.
	 * 
	 * @return The database connection.
	 * @throws DAOException
	 * @throws RuntimeException if unable to connect to the database.
	 */
	public static Connection getConnection() throws DAOException {
		Connection con = null;

		String url;
		String userName;
		String passWord;

		if (System.getenv("CI") != null) {
			url = System.getenv("DATABASE_HOST");
			userName = System.getenv("DATABASE_USERNAME");
			passWord = System.getenv("DATABASE_PASSWORD");
		} else {
			Dotenv env = Dotenv.load();
			url = env.get("DATABASE_HOST");
			userName = env.get("DATABASE_USERNAME");
			passWord = env.get("DATABASE_PASSWORD");
		}

		try {
			con = DriverManager.getConnection(url, userName, passWord);

		} catch (Exception e) {
			throw new DAOException("Unable to connect to the database");
		}
		return con;
	}

	public static void close(Connection conn, Statement stmt, ResultSet rs) {
		Logger logger = new Logger();
		try {
			if (rs != null) {
				rs.close();
			}
			if (stmt != null) {
				stmt.close();
			}
			if (conn != null) {
				conn.close();
			}
		} catch (SQLException e) {
			logger.info(e.getMessage());
		}
	}

}
```
@Sasikumar77  Replace this with your code, Hope this will work

**Comment by Sasikumar77** [comment]
Thanks @cyber-sparky , this bug was gone and testcase run well, thank you for helped to resolving this issue.
